version: '2'

services:
  cache:
    build: docker-files/redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379
    volumes:
      - ${PWD}/data/cache:/data